version: "3.8"
services:
  backend: 
    build: ./
    ports:
      - 8080:8080
    environment: 
      DB_URL: mongodb://database/wanted-emoji-db
  database: 
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes: 
      - wanted-emoji-vol:/data/db
volumes: 
  wanted-emoji-vol:

